### PR TITLE
[Work in Progress] Selectable Cells

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes selection on cells without the use of an overlay view. 

Credit to Pero Matic for the solution.

### CODE REVIEW

**Comment by ashfurrow** [comment]
[FIXED] Currently broken; when cells become highlighted, the otherwise invisible "more" and "delete" text appears. Would welcome solutions here. 
screen shot 2013-10-29 at 10 22 42 am

**Comment by aout** [comment]
Hi there,
I played with your cell recently and noticed that in case of subclassing the custom scroll view would't be able to forward the events to self.tableViewCell.
I found a workaround by changing a bit the process but I'm not sure it's viable.
Instead of forwarding events to a property, the scrollView forwards to its superview.

**Comment by ashfurrow** [comment]
Cool! Can you send a pull request so I can take a look?

**Comment by davedelong** [comment]
A couple of thoughts:
- you could hide the buttons unless the scrollview's contentOffset is non-zero
- if the scrollview is dragging, you'll probably want to cancel the touches in the cell; otherwise you may end up selecting the cell while you scroll

**Comment by ashfurrow** [comment]
Going to close this so my open PR list is finally clean. The company no longer exists, so it's never likely to be merged anyhow.

**Pull request closed without merging**
